[project]
name = "tt-bootcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "faker>=35.0.0",
    "ruff>=0.9.3",
    "tqdm>=4.67.1",
]
